config/routes.rb
Rails.application.routes.draw do

  root :to => "products#index"

  resources :products do
    resources :reviews, :only => [:show, :create, :destroy]
  end

  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :description, :name, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}

  has_many :reviews
  has_many :users, :through => :reviews

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :reviews
  has_many :products, :through => :reviews
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end

  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # leaving this in preventing users from seeing products
  # before_filter :ensure_logged_in, :only => [:show]

  def index
    @products = Product.all
  end

  def show
    begin
      @product = Product.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to "/"
    rescue ActiveRecord::CatchAll
      #Only comes in here if nothing else catches the error
      redirect_to "/"
    end
    if current_user
      @review = @product.reviews.build
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :price_in_cents)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :ensure_logged_in, :only => [:edit, :create, :show, :update, :destroy]
  before_filter :load_product

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user_id = current_user.id

    # Check out this article on [.build](http://stackoverflow.com/questions/783584/ruby-on-rails-how-do-i-use-the-active-record-build-method-in-a-belongs-to-rel)
    # You could use a longer alternate syntax if it makes more sense to you
    #
    # @review = Review.new(
    #   :comment    => params[:review][:comment],
    #   :product_id => @product.id,
    #   :user_id    => current_user.id
    # )

    if @review.save
      redirect_to products_path, notice: 'Review created successfully'
    else
      render 'products/show'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private
    def review_params
      params.require(:review).permit(:comment, :product_id)
    end

    def load_product
      @product = Product.find(params[:product_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to products_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforestly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
  <p id="alert"><%= flash[:alert] %></p>
<% end %>

<%= yield %>

<p class="userinfo">
  <% if current_user %>
    Signed in as <%= current_user.name %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
  <% else %>
    <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
  <% end %>
</p>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<div class="uk-container uk-width-1-1 uk-container-center uk-margin-top">
  <div class="uk-width-small-2-5 uk-float-left uk-hidden-small"><h1 class="uk-margin-small-top" style="font-size: 4em;">Rainforest<strong><em>ly</em></strong></h1></div>
  <nav class="uk-navbar uk-float-right uk-width-small-1-1 uk-width-medium-3-6 uk-width-large-3-5 uk-display-inline-block uk-margin-small-top">
    <ul class="uk-navbar-nav uk-navbar-flip uk-hidden-small">
      <li>
          <a href="/">About</a>
      </li>
      <li>
          <a href="">Signup | Login</a>
      </li>
      <li>
          <a href="/">Contact</a>
      </li>
    </ul>
    <div id="my-id" class="uk-offcanvas uk-visible-small">
      dsadasdadas
    </div>
    <a href="#my-id" class="uk-visible-small uk-navbar-toggle" data-uk-offcanvas></a>
    <div class="uk-navbar-brand uk-navbar-center uk-visible-small" style="font-size: 1.6em; padding-top: 5px;">Rainforest<strong><em>ly</em></strong></div>
    </div>
  </nav>
</div>
<div class="uk-container uk-container-center">
  <hr class="uk-width-1-1 uk-margin-bottom">

  <div class="uk-width-1-1" style="padding: 0;">
    <div class="uk-grid">
      <!-- Feature -->
      <!-- <div class="uk-width-small-1-2 uk-width-medium-2-4 uk-width-large-2-4 uk-float-right uk-margin-bottom">
        <div class="uk-panel uk-panel-box uk-float-right">
          <div class="uk-panel-teaser">
             <img src="http://placehold.it/500x500" alt"">
          </div>
        </div>
      </div> -->
      <!-- 4x4 Grid -->

      <% @products.each do |product| %>
      <div class="uk-width-small-2-4 uk-width-medium-1-3 uk-width-large-1-4 uk-margin-bottom">
        <div class="uk-panel uk-panel-box">
          <div class="uk-panel-teaser">
            <%= link_to image_tag(product.photo_url, :class => "img"), product %>
          </div>
        <p><%= product[:description] %></p>
        <div class="uk-panel-badge uk-badge uk-badge-notification uk-badge-danger" style="top: -10px; right: -20px;  padding: 8px;"><div style="float: left; line-height: 12px; margin: 0 2px 0 0;">$ </div><div style="float: right; font-size: 1.5em;"><%= product.formatted_price.to_f.round %></div></div>
        <button class="uk-button uk-button-primary uk-button-mini" type="button">Buy me</button>
        </div>
      </div>
      <% end %>

    </div>
  </div>
</div>

<!-- <ul class="uk-grid" data-uk-grid-margin>
  <li class="uk-width-small-2-4 uk-width-medium-1-4 uk-panel uk-panel-box">
    <h3>Product name</h3>
    <div class="uk-panel-badge uk-badge uk-badge-notification uk-badge-success">00.00</div>
    <img src="">
    <hr>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum unde nemo modi et animi. Iusto nemo sint laborum cum, eos rerum ducimus quos fugiat quibusdam eum sed quas doloremque, dolorum.</p>
  </li>
</ul> -->

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

<h3><%= @product.name %> (<%= @product.formatted_price %>) (<%= @product.price_in_cents %>)</h3>
<h2><%= link_to "#{@product.description}", @product %>

<h3>Reviews</h3>

<p>Reviews for <%= @product.name %></p>

<% @product.reviews.each do |review| %>
  <p>
    <%= review.comment %>
    <br>
    <% if review.user != nil %>
      <em> by <%= review.user.email %></em>
      Added on: <%= review.created_at %>
    <% end %>
  </p>
<% end %>

<% if current_user %>

  <h4>New Review</h4>

  <%= render 'reviews' %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>